platform :ios, '13.0'

use_frameworks!

target 'app' do
	pod 'IQKeyboardManagerSwift'
	pod 'SkyFloatingLabelTextField'
	pod 'UICircularProgressRing'
	pod 'SoundWave'
	pod 'Magnetic'
	pod 'Kingfisher'
end
